import type { Transaction } from "./types";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

/** Static seed for charts and demos — not meant to change between reloads before hydration */
export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    date: daysAgo(85),
    amount: 3300,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "t2",
    date: daysAgo(82),
    amount: 120,
    category: "Transport",
    type: "expense",
    description: "Transit pass",
  },
  {
    id: "t3",
    date: daysAgo(78),
    amount: 340,
    category: "Food",
    type: "expense",
    description: "Groceries",
  },
  {
    id: "t4",
    date: daysAgo(70),
    amount: 2200,
    category: "Freelance",
    type: "income",
    description: "Design project",
  },
  {
    id: "t5",
    date: daysAgo(65),
    amount: 95,
    category: "Entertainment",
    type: "expense",
    description: "Concert tickets",
  },
  {
    id: "t6",
    date: daysAgo(58),
    amount: 210,
    category: "Bills",
    type: "expense",
    description: "Internet",
  },
  {
    id: "t7",
    date: daysAgo(55),
    amount: 3300,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "t8",
    date: daysAgo(50),
    amount: 180,
    category: "Food",
    type: "expense",
    description: "Dining out",
  },
  {
    id: "t9",
    date: daysAgo(45),
    amount: 1200,
    category: "Shopping",
    type: "expense",
    description: "Laptop accessories",
  },
  {
    id: "t10",
    date: daysAgo(40),
    amount: 450,
    category: "Health",
    type: "expense",
    description: "Pharmacy & checkup",
  },
  {
    id: "t11",
    date: daysAgo(32),
    amount: 2200,
    category: "Freelance",
    type: "income",
    description: "Consulting",
  },
  {
    id: "t12",
    date: daysAgo(28),
    amount: 3300,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "t13",
    date: daysAgo(24),
    amount: 62,
    category: "Transport",
    type: "expense",
    description: "Rideshare",
  },
  {
    id: "t14",
    date: daysAgo(18),
    amount: 290,
    category: "Food",
    type: "expense",
    description: "Groceries",
  },
  {
    id: "t15",
    date: daysAgo(14),
    amount: 165,
    category: "Bills",
    type: "expense",
    description: "Utilities",
  },
  {
    id: "t16",
    date: daysAgo(10),
    amount: 75,
    category: "Entertainment",
    type: "expense",
    description: "Streaming",
  },
  {
    id: "t17",
    date: daysAgo(7),
    amount: 3300,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "t18",
    date: daysAgo(4),
    amount: 420,
    category: "Shopping",
    type: "expense",
    description: "Clothing",
  },
  {
    id: "t19",
    date: daysAgo(3),
    amount: 2400,
    category: "Investment",
    type: "income",
    description: "Dividends & distributions",
  },
  {
    id: "t20",
    date: daysAgo(1),
    amount: 88,
    category: "Food",
    type: "expense",
    description: "Coffee & lunch",
  },
];
